# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.BooleanField(default=False)),
                ('deposito', models.FloatField(default=0.0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=100)),
                ('existencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlCajasEntregadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Caja')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.AgendaActividades')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_recoleccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('valor_envio', models.FloatField()),
                ('valor_adicional', models.FloatField(null=True)),
                ('emplasticado', models.BooleanField(default=False)),
                ('valor_emplasticado', models.FloatField()),
                ('quien_recibe', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('cajas', models.CharField(max_length=1000)),
                ('total', models.FloatField()),
                ('imagen', models.ImageField(default='paquetes/eehn.png', upload_to='paquetes/imagen/', verbose_name='Imagen del envio')),
                ('pago_recibido', models.FloatField()),
                ('credito', models.BooleanField(default=False)),
                ('ticket', models.BooleanField(default=False)),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateField(auto_now_add=True)),
                ('cantidad', models.FloatField()),
                ('descripcion', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('codigo_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Envio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EstadoEnvio')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('codigo_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Envio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EstadoEnvio')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoGasto'),
        ),
        migrations.AddField(
            model_name='envio',
            name='pais_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pais'),
        ),
        migrations.AddField(
            model_name='envio',
            name='quien_envia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente'),
        ),
        migrations.AddField(
            model_name='envio',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pais'),
        ),
        migrations.AddField(
            model_name='agendaactividades',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente'),
        ),
        migrations.AddField(
            model_name='agendaactividades',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
