# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.FloatField()),
                ('saldo', models.FloatField()),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='saldo_pendiente',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagoscredito',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Envio'),
        ),
    ]
