# Generated by Django 3.2.15 on 2023-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajapais',
            name='empresa',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
