# Generated by Django 3.2.15 on 2023-04-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_cajapais_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleenvio',
            name='estado_hija',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='principal.estadoenvio'),
        ),
    ]
