# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20181103_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaactividades',
            name='cierre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendaactividades',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='agendaactividades',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='cierre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendaactividades',
            name='hora',
            field=models.CharField(max_length=50),
        ),
    ]
