# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_agendaactividades_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaactividades',
            name='fecha_realizo',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
