# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_agendaactividades_fecha_realizo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscredito',
            name='tipo_pago',
            field=models.BooleanField(default=True),
        ),
    ]
