# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-14 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_pagoscredito_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscredito',
            name='cierre',
            field=models.BooleanField(default=False),
        ),
    ]
