# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-14 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0007_pagoscredito_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscredito',
            name='usuario_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
