# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_pagoscredito_usuario_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscredito',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
