# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_pagoscredito_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaactividades',
            name='fue_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
