# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_agendaactividades_fue_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaactividades',
            name='descripcion_entrega',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
