# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-10 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_agendaactividades_descripcion_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaactividades',
            name='actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.Actividad'),
        ),
    ]
