# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_agendaactividades_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaactividades',
            name='actividad',
        ),
        migrations.AddField(
            model_name='agendaactividades',
            name='es_entregar',
            field=models.BooleanField(default=False),
        ),
    ]
