# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-11 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0013_auto_20191210_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboContenedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pasaporte', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono_adicional', models.CharField(blank=True, max_length=15, null=True)),
                ('pais_destino', models.CharField(blank=True, max_length=15, null=True)),
                ('puerto_destino', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_recibe', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_recibe', models.CharField(blank=True, max_length=50, null=True)),
                ('nip_rtn', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_contenedor', models.FloatField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='archivos_pdf/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReciboVehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pasaporte', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono_adicional', models.CharField(blank=True, max_length=15, null=True)),
                ('pais_destino', models.CharField(blank=True, max_length=15, null=True)),
                ('puerto_destino', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_recibe', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_recibe', models.CharField(blank=True, max_length=50, null=True)),
                ('nip_rtn', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_contenedor', models.FloatField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='archivos_pdf/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
