# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_recibocontenedor_recibovehiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocontenedor',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pdf_contenedores/'),
        ),
        migrations.AlterField(
            model_name='recibovehiculos',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pdf_vehiculos/'),
        ),
    ]
