# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20191211_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibovehiculos',
            name='valor_contenedor',
        ),
        migrations.AddField(
            model_name='recibocontenedor',
            name='tamano_contenedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='marca_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='modelo_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='vin_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
