# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_recibocontenedor_recibo_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibovehiculos',
            name='recibo_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
