# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-12 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_recibovehiculos_recibo_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibovehiculos',
            name='valor_vehiculo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
