# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-08 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0019_recibovehiculos_valor_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo_no', models.CharField(blank=True, max_length=100, null=True)),
                ('size_caja', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_caja', models.FloatField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='archivos_pdf_caja/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
