# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-08 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0021_auto_20200108_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revendedor',
            name='guia_empresa',
        ),
        migrations.AddField(
            model_name='envio',
            name='guia_revendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='revenedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revendedor',
            name='usuario_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_registro_revendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
