# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20200108_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='revendedor',
            name='es_revendedor',
            field=models.BooleanField(default=True),
        ),
    ]
