# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-08 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_revendedor_es_revendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revendedor',
            name='es_revendedor',
        ),
    ]
