# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-08 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_revendedor_es_revendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='revenedor',
            new_name='revendedor',
        ),
    ]
