# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_auto_20200108_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='cierre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibocontenedor',
            name='cierre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibocontenedor',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='cierre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='fecha_cierre',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envio',
            name='valor_adicional',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='valor_emplasticado',
            field=models.FloatField(default=0.0),
        ),
    ]
