# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_auto_20200110_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
