# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_envio_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
