# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0030_envio_usuario_aprobo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocontenedor',
            name='nombre_recibe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recibocontenedor',
            name='num_pasaporte',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recibocontenedor',
            name='telefono_recibe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recibovehiculos',
            name='marca_vehiculo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recibovehiculos',
            name='modelo_vehiculo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recibovehiculos',
            name='nombre_recibe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recibovehiculos',
            name='num_pasaporte',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recibovehiculos',
            name='telefono_recibe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recibovehiculos',
            name='vin_vehiculo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
