# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-01 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0031_auto_20200116_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendaactividades',
            name='descripcion_entrega',
        ),
        migrations.RemoveField(
            model_name='agendaactividades',
            name='es_entregar',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='revendedor',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='guia_revendedor',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='revendedor',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='usuario_aprobo',
        ),
        migrations.AlterField(
            model_name='envio',
            name='valor_adicional',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='valor_emplasticado',
            field=models.FloatField(),
        ),
    ]
