# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0032_auto_20200401_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteRecibe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('pais', models.CharField(blank=True, max_length=300, null=True)),
                ('departamento', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_empleado', models.CharField(max_length=50)),
                ('apellidos_empleado', models.CharField(max_length=50)),
                ('telefono_empleado', models.CharField(max_length=50)),
                ('correo_empleado', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(max_length=5)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('slogan_empresa', models.CharField(max_length=100)),
                ('logo_empresa', models.FileField(blank=True, null=True, upload_to='logo_empresa/')),
                ('direccion_empresa', models.CharField(max_length=200)),
                ('telefono_empresa', models.CharField(max_length=100)),
                ('celular_empresa', models.CharField(max_length=100)),
                ('correo_empressa', models.EmailField(max_length=254)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=50)),
                ('descripcion_pedido', models.CharField(max_length=300, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('deposito', models.FloatField(default=0.0)),
                ('cierre', models.BooleanField(default=False)),
                ('fecha_realizo', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(auto_now_add=True)),
                ('descripcion_entrega', models.CharField(max_length=300, null=True)),
                ('actividad', models.BooleanField()),
                ('recibo_entrega', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaControlCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida_caja', models.CharField(default='', max_length=50)),
                ('compra', models.IntegerField(default=0)),
                ('existencia', models.IntegerField(default=0)),
                ('recibo_no', models.CharField(default='', max_length=50)),
                ('valor', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('recibo', models.FileField(blank=True, null=True, upload_to='archivos_compra_cajas/')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_caja_usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaDetalleCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('recibo_no', models.CharField(default='', max_length=50)),
                ('valor', models.FloatField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('recibo', models.FileField(blank=True, null=True, upload_to='archivos_compra_cajas/')),
                ('accion', models.BooleanField(default=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EmpresaControlCaja')),
                ('recibo_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.ReciboCaja')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_caja_usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaDiaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('valor_apertura', models.FloatField()),
                ('valor_cierre', models.FloatField()),
                ('valor_efectivo', models.FloatField()),
                ('faltante', models.FloatField(default=0.0)),
                ('codigo_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_dia_usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_empleado_usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('recibo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='archivos_gastos/')),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio', models.FloatField(default=0.25)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaTipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensaje', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.RemoveField(
            model_name='agendaactividades',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='agendaactividades',
            name='usuario_registro',
        ),
        migrations.RemoveField(
            model_name='controlcajasentregadas',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='controlcajasentregadas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='tipo_gasto',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='telefonos',
            new_name='celular_registrar',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='cajas',
            new_name='descripcion_embarque',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='direccion',
            new_name='direccion_registrar',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='quien_recibe',
            new_name='quien_recibev',
        ),
        migrations.AddField(
            model_name='cliente',
            name='revendedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envio',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envio',
            name='guia_revendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='revendedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='envio',
            name='revendedor_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Revendedor'),
        ),
        migrations.AddField(
            model_name='envio',
            name='usuario_aprobo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_aprobo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AgendaActividades',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='ControlCajasEntregadas',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.DeleteModel(
            name='TipoGasto',
        ),
        migrations.AddField(
            model_name='empresamensaje',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Envio'),
        ),
        migrations.AddField(
            model_name='empresamensaje',
            name='tipo_mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.TipoMensajes'),
        ),
        migrations.AddField(
            model_name='empresagasto',
            name='tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EmpresaTipoGasto'),
        ),
        migrations.AddField(
            model_name='empresagasto',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_gasto_usuario_registro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaactividades',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente'),
        ),
        migrations.AddField(
            model_name='empresaactividades',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
        migrations.AddField(
            model_name='empresaactividades',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_agenda_usuario_registro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Rol'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_usuario_registro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienterecibe',
            name='cliente_envia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente'),
        ),
        migrations.AddField(
            model_name='clienterecibe',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_recibe_usuario_registro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Estados'),
        ),
        migrations.AddField(
            model_name='envio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo_contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.TipoContenido'),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.TipoEnvio'),
        ),
        migrations.AddField(
            model_name='estadoenvio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
        migrations.AddField(
            model_name='recibocontenedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
        migrations.AddField(
            model_name='seguimientoenvio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Empresa'),
        ),
    ]
