# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0033_auto_20200402_2319'),
    ]

    operations = [

    ]
