# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0034_envio_valor_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='quien_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.ClienteRecibe'),
        ),
    ]
