# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0035_auto_20200402_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('correo', models.CharField(blank=True, max_length=254, null=True)),
                ('revendedor', models.BooleanField()),
            ],
            options={
                'db_table': 'sistema_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaClienterecibe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('departamento', models.CharField(blank=True, max_length=300, null=True)),
                ('pais', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'sistema_clienterecibe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sistema_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(max_length=5)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('slogan_empresa', models.CharField(max_length=100)),
                ('logo_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_empresa', models.CharField(max_length=200)),
                ('telefono_empresa', models.CharField(max_length=100)),
                ('celular_empresa', models.CharField(max_length=100)),
                ('correo_empressa', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'sistema_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaEmpresaenvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_recoleccion', models.DateTimeField()),
                ('fecha_envio', models.DateField()),
                ('descripcion_embarque', models.CharField(max_length=1000)),
                ('valor_envio', models.FloatField()),
                ('valor_adicional', models.FloatField()),
                ('valor_emplasticado', models.FloatField()),
                ('total', models.FloatField()),
                ('pago_recibido', models.FloatField()),
                ('saldo_pendiente', models.FloatField()),
                ('emplasticado', models.BooleanField()),
                ('credito', models.BooleanField()),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('ticket', models.BooleanField()),
                ('cierre', models.BooleanField()),
                ('cancelado', models.BooleanField()),
                ('fecha_cierre', models.DateField()),
                ('revendedor', models.BooleanField()),
                ('guia_revendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado', models.BooleanField()),
                ('direccion_registrar', models.CharField(blank=True, max_length=1000, null=True)),
                ('celular_registrar', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_seguro', models.FloatField()),
            ],
            options={
                'db_table': 'sistema_empresaenvio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaEmpresaestadoenvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sistema_empresaestadoenvio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sistema_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaHistorialenvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sistema_historialenvio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaPais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sistema_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaRevendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(max_length=254)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('es_revendedor', models.BooleanField()),
            ],
            options={
                'db_table': 'sistema_revendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaSeguimientoenvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sistema_seguimientoenvio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaTipocontenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sistema_tipocontenido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaTipoenvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sistema_tipoenvio',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='descripcion_entrega',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
