# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_auto_20200426_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='valor_seguro',
            field=models.FloatField(default=0.0),
        ),
    ]
