# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-26 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_auto_20200426_2204'),
        ('principal', '0036_envio_valor_seguro'),
    ]

    operations = [
    ]
