# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0037_merge_20200426_2323'),
    ]

    operations = [

    ]
