# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0038_auto_20200523_2059'),
        ('principal', '0037_envio_valor_seguro'),
    ]

    operations = [
    ]
