# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0039_merge_20200528_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='revenedor_creo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Revendedor'),
        ),
    ]
