# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-24 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0041_sistemaempresamensaje_sistematipomensajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaPais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('esta_en_transito', models.BooleanField(default=False)),
                ('estado_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.EstadoEnvio')),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_original', models.CharField(max_length=100)),
                ('codigo_express', models.CharField(max_length=100)),
                ('pies_cubicos', models.FloatField(default=0.0)),
                ('observacion', models.CharField(max_length=100)),
                ('fecha_ingreso_houston', models.DateTimeField(auto_now_add=True)),
                ('fecha_ingreso_puerto_houston', models.DateTimeField(auto_now_add=True)),
                ('fecha_transito_maritimo', models.DateTimeField(auto_now_add=True)),
                ('fecha_puerto_honduras', models.DateTimeField(auto_now_add=True)),
                ('fecha_bodega_honduras', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.EstadoEnvio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0.0)),
                ('cantidad', models.IntegerField(default=0)),
                ('codigo_orden', models.IntegerField(default=0)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('fue_enviada', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0.0)),
                ('fue_subida_camion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialContenedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=100)),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Contenedor')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.EstadoEnvio')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('largo', models.FloatField(default=0.0)),
                ('ancho', models.FloatField(default=0.0)),
                ('alto', models.FloatField(default=0.0)),
                ('espacio_cubico', models.FloatField(default=0.0)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='clienterecibe',
            name='departamento_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Departamento'),
        ),
        migrations.AddField(
            model_name='clienterecibe',
            name='pais_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Pais'),
        ),
        migrations.AddField(
            model_name='envio',
            name='estado_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.EstadoEnvio'),
        ),
        migrations.AddField(
            model_name='envio',
            name='firma_cliente',
            field=models.ImageField(blank=True, default='paquetes/eehn.png', null=True, upload_to='cliente/firma/', verbose_name='Firma Cliente'),
        ),
        migrations.AddField(
            model_name='pais',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='precio_pulgada_caja',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='prueba_dato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibovehiculos',
            name='prueba_dato_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='descripcion_embarque',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detalleenvio',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Envio'),
        ),
        migrations.AddField(
            model_name='detalleenvio',
            name='tipo_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.CajaPais'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='pais_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pais'),
        ),
        migrations.AddField(
            model_name='cajapais',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Pais'),
        ),
        migrations.AddField(
            model_name='cajapais',
            name='tipo_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.TipoCaja'),
        ),
        migrations.AddField(
            model_name='cajapais',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envio',
            name='camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Camion'),
        ),
        migrations.AddField(
            model_name='envio',
            name='contenedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Contenedor'),
        ),
        migrations.AddField(
            model_name='pagoscredito',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.UbicacionEmpleado'),
        ),
    ]
